### ISSUE TITLE
Wrong calculations

### ISSUE THREAD

**Issue by ipsissimus** [oshibka404/ohooligans#10]

**Comment by ipsissimus** [comment]
![image](https://user-images.githubusercontent.com/11952546/54434630-c7ac9980-473f-11e9-908f-ce16dbd4504c.png)

Как видно на чеке общая сумма к оплате 2468. Всего было 5 человек, используя калькулятор получилось
Person 1: 441р
Person 2: 441р
Person 3: 441р
Person 4: 707р
Person 5: 420р

Общая сумма получилась 2450. Итого не хватает 18 рублей! ~~где деньги Зин?~~

**Comment by oshibka404** [comment]
расследование, проведённое сообществом, показало, что расчеты работают корректно.
стоит подумать о том, как переделать юикс чтобы было понятно что к чему.
